# Numpy module 

In [9]:
# 1) Standard Way

import numpy   # importing modules
y=[1,2,3,4]
x=numpy.array(y)
print(x)
print(type(x))  # printing type of array
print(x.ndim)   # To find dimension

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [13]:
# 2) Using Alias

import numpy as np
y=[1,2,3,4]
x=np.array(y)
print(x)
print(type(x))
print(x.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [12]:
# 3) Along with numpy

from numpy import array
y=[1,2,3,4]
x=array(y)
print(x)
print(type(x))
print(x.ndim)


[1 2 3 4]
<class 'numpy.ndarray'>
1
