# Special type of array

In [2]:
# Arrays with '0's

import numpy as np   # importing module
ar_zero = np.zeros(4)    # Passing value is the number of elements np.zeros(number of elements) in 1D array
ar1_zero = np.zeros((3,4))  # Passing value 3 is row and 4 is column np.zeros(row,column) in 2-D array
print(ar_zero)
print( )
print(ar1_zero)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
# Arrays filled with 1's

ar2_one = np.ones(4)    # Passing value is the number of elements np.ones(number of elements) in 1D array
ar3_one = np.ones((3,4))  # Passing value 3 is row and 4 is column np.ones(row,column) in 2-D array
print(ar2_one)
print( )
print(ar3_one)


[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
# To create an empty array

ar_emp = np.empty(4)    # Passing value is the number of elements np.empty(number of elements) in 1D array
ar1_emp = np.empty((3,4))  # Passing value 3 is row and 4 is column np.empty(row,column) in 2-D array
print(ar_emp)
print( )
print(ar1_emp)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
# An array with range of elements

ar_element = np.arange(4)    # Passing value is that np.arange(till upto from 0 and given num is not include) in 1D array
ar1_element = np.arange(4,10)  # passing value is np.arange(start,end not include)
print(ar_element)
print( )
print(ar1_element)


[0 1 2 3]

[4 5 6 7 8 9]


In [14]:
# Array diagonal element is filled with 1's like identity matrix

ar_dia = np.eye(3)    # Passing value is that np.eye(by default make array )
ar1_dia = np.eye(3,4)  # passing value is np.eye(row,column)
print(ar_dia)
print( )
print(ar1_dia)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [17]:
# Create an array with values that are spaced linearly in a specified interval

myarr = np.linspace(5,20,num=4)  # passing value is np.linspace(min,max,number of values)
print(myarr)

[ 5. 10. 15. 20.]
