# Dimension of array in Numpy

In [3]:
# 1 ) To declare 1-D array

import numpy as np
myarray = np.array([10,20,30,40,50])   # 1-D array
print(myarray)
print(myarray.ndim)  # Gives dimension of array

[10 20 30 40 50]
1


In [4]:
# 2) To declare 2-D array

myarr1 = np.array([[100,200,300,400,500]])  # 2-D array
print(myarr1)
print(myarr1.ndim)   # Gives dimension of array

[[100 200 300 400 500]]
2


In [7]:
# 3) To declare 3-D array

myarr2 = np.array([[[1000,2000,3000,4000,5000]]])
print(myarr2)
print(myarr2.ndim)  # Gives dimension of array

[[[1000 2000 3000 4000 5000]]]
3
